extra.set("kotlin_version", "1.5.31")
extra.set("tornadofx_version", "1.7.20")
extra.set("jfx_version", "17.0.1")
extra.set("bouncycastle_version", "1.69")
extra.set("zxing_version", "3.4.1")
extra.set("javax_json_version", "1.1.4")